# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yifan Chen
title: CU Boulder
email: yich7110@colorado.edu
# website: https://github.com/CCatherineeeee/CCatherineeeee.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  CCatherineeeee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: yifanchen42
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: 
about_content: | # this will include new lines to allow paragraphs
  Hi! My name's Yifan Chen. You can also call me Catherine. I'm currently studying in CU Boulder as a Computer Science major and always wandering over the Engineering Building with my mates. I'm interested in database, as well as software app and data science.

  <mark>Python</mark> is my favorate language. I'm also self-learning <mark>Java</mark> right now. There are always new things to explore in this world.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Data Collector Web Application
        link: 
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This website application collect user input data and sent result to user's input email address. The home page and success result page in build with This application is build with <mark>HTML</mark>, <mark>CSS</mark>, and <mark>Flask</mark>. All the data is stored with <mark>PostSQL</mark> database. The application will conduct statistical result with PostSQL and send email by applying MIMEText.
          This is my first time to learn and apply Flask. Flask is a <mark>Python</mark> web application framework. I was very superised and amazed to learn how efficient Flask is!

      - layout: top-middle
        title: Veterinary Clinic Case Study
        link: 
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I conducted this case study while I was learning about Database System with my Professor. I started the very beginning which is to design data model with <mark>MySQL</mark> Workbench, built the database by generating Data Definition Language from data model. 
          
      - layout: top-middle
        title: Tinner
        link: github.com/ryke7507/Tinner
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fab fa-github
            url: github.com/ryke7507/Tinner
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Tinner is a web application that will give you recommendation on what to have for dinner. I built the profile page using <mark>Bootstrap</mark> and <mark>HTML</mark>.
          This is a team project. We use Agile as our workflow to keep our project on track.
          
      - layout: top-middle
        title: Space Invader
        link: github.com/yugo9081/Space_Invaders
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fab fa-github
            url: github.com/yugo9081/Space_Invaders
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Space Invader is a 2D shootingi arcade game powered by <mark>Unity</mark>. This is also a team program and my part is to design model for bullet and asteroid (obstacle) model. I also adopet the coding part with <mark>C#</mark>
          It's my first time to work with Unity and C#. It's also the first project for HAWC - our computer science interest group. I'll introduce more about us below!
          
      - layout: top-middle
        title: Pokédex
        link: 
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a data structure application programmed with <mark>C++</mark>that run on terminal. Players can encounter all kinds of Pokémon in Kanto region (Yep, this is Pokémon Red, Blue and Yellow and their remakes).

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Course Assistant
        link: 
        sub_title: 
        caption: January 2021 - Current
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            I hold office hour as a CA for helping student solve their problem as well as attend weekly meeting to discuss with teaching faculty and other CAs. This practiced my problem solving skills. It's also an interesting experience to share and learn on other student's ideas.
            
      - layout: left
        title: Mindscribe
        link: www.mindscribe.org
        sub_title: Data Analysis Research Assistant
        caption: September 2020 - December 2020
        quote: >
          MindScribe is on a mission to help young children tell their stories.
        description: | # this will include new lines to allow paragraphs
            At Mindscribe, we learn and reflect on how child-robot interaction may support metacognitive skills. I utilize data visualization tools and perform data analysis while perform data analysis with statistical background. This is very a cool team and cool project.

            
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Colorado Boulder
        sub_title: B.S. in Computer Science
        caption: Anticipated Graduation 2022
        description: |
          During my time at Boulder, I learnt a lot of skills and completed several group projects. I enjoyed my time and learnt a lot about a healthy work life balance.
          Coursework that have completed: Data Strucutres, Algorithms, Data Science, Principle of Programming Language, Database System, AI(current), Robotics(current)
          
  
  - title: Leadership
    layout: text
    content: | # this will include new lines to allow paragraphs
      We are all women who are passionate about learning enw things and working on common passion projects together. We built independent projects such as Space Invader (listed above!). We also attended several Hackathon such as T9 and HackCU. We share cool ideas together and explore the fun in coding. I'm very glad to be the cofounder and have our awesome members. 
     


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
